//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamagotchi
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Hunger { get; set; }
        public int Sleep { get; set; }
        public int Boredom { get; set; }
        public int Health { get; set; }
        public System.DateTime LastAccess { get; set; }
    }
}
