//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiApp.Tamagotchi_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/TamagotchiService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tamagotchi", Namespace="http://schemas.datacontract.org/2004/07/TamagotchiWebService")]
    [System.SerializableAttribute()]
    public partial class Tamagotchi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BoredomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BusyTillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HealthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HungerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAliveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SleepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TamagotchiApp.Tamagotchi_Service.State StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Boredom {
            get {
                return this.BoredomField;
            }
            set {
                if ((this.BoredomField.Equals(value) != true)) {
                    this.BoredomField = value;
                    this.RaisePropertyChanged("Boredom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BusyTill {
            get {
                return this.BusyTillField;
            }
            set {
                if ((this.BusyTillField.Equals(value) != true)) {
                    this.BusyTillField = value;
                    this.RaisePropertyChanged("BusyTill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Health {
            get {
                return this.HealthField;
            }
            set {
                if ((this.HealthField.Equals(value) != true)) {
                    this.HealthField = value;
                    this.RaisePropertyChanged("Health");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hunger {
            get {
                return this.HungerField;
            }
            set {
                if ((this.HungerField.Equals(value) != true)) {
                    this.HungerField = value;
                    this.RaisePropertyChanged("Hunger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAlive {
            get {
                return this.IsAliveField;
            }
            set {
                if ((this.IsAliveField.Equals(value) != true)) {
                    this.IsAliveField = value;
                    this.RaisePropertyChanged("IsAlive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastAccess {
            get {
                return this.LastAccessField;
            }
            set {
                if ((this.LastAccessField.Equals(value) != true)) {
                    this.LastAccessField = value;
                    this.RaisePropertyChanged("LastAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sleep {
            get {
                return this.SleepField;
            }
            set {
                if ((this.SleepField.Equals(value) != true)) {
                    this.SleepField = value;
                    this.RaisePropertyChanged("Sleep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TamagotchiApp.Tamagotchi_Service.State State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/TamagotchiWebService")]
    [System.SerializableAttribute()]
    public partial class State : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusyMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanPerformActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HighestPropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HighestPropertyMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusyMessage {
            get {
                return this.BusyMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.BusyMessageField, value) != true)) {
                    this.BusyMessageField = value;
                    this.RaisePropertyChanged("BusyMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanPerformAction {
            get {
                return this.CanPerformActionField;
            }
            set {
                if ((this.CanPerformActionField.Equals(value) != true)) {
                    this.CanPerformActionField = value;
                    this.RaisePropertyChanged("CanPerformAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HighestProperty {
            get {
                return this.HighestPropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.HighestPropertyField, value) != true)) {
                    this.HighestPropertyField = value;
                    this.RaisePropertyChanged("HighestProperty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HighestPropertyMessage {
            get {
                return this.HighestPropertyMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.HighestPropertyMessageField, value) != true)) {
                    this.HighestPropertyMessageField = value;
                    this.RaisePropertyChanged("HighestPropertyMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Tamagotchi_Service.ITamagotchiService")]
    public interface ITamagotchiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITamagotchiService/GetDataUsingDataContractResponse")]
        TamagotchiApp.Tamagotchi_Service.CompositeType GetDataUsingDataContract(TamagotchiApp.Tamagotchi_Service.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITamagotchiService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.CompositeType> GetDataUsingDataContractAsync(TamagotchiApp.Tamagotchi_Service.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/ResetTamagotchies", ReplyAction="http://tempuri.org/ITamagotchiService/ResetTamagotchiesResponse")]
        void ResetTamagotchies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/ResetTamagotchies", ReplyAction="http://tempuri.org/ITamagotchiService/ResetTamagotchiesResponse")]
        System.Threading.Tasks.Task ResetTamagotchiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetAllTamagotchies", ReplyAction="http://tempuri.org/ITamagotchiService/GetAllTamagotchiesResponse")]
        TamagotchiApp.Tamagotchi_Service.Tamagotchi[] GetAllTamagotchies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetAllTamagotchies", ReplyAction="http://tempuri.org/ITamagotchiService/GetAllTamagotchiesResponse")]
        System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.Tamagotchi[]> GetAllTamagotchiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/GetTamagotchiResponse")]
        TamagotchiApp.Tamagotchi_Service.Tamagotchi GetTamagotchi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/GetTamagotchiResponse")]
        System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.Tamagotchi> GetTamagotchiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/AddTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/AddTamagotchiResponse")]
        void AddTamagotchi(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/AddTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/AddTamagotchiResponse")]
        System.Threading.Tasks.Task AddTamagotchiAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Eat", ReplyAction="http://tempuri.org/ITamagotchiService/EatResponse")]
        void Eat(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Eat", ReplyAction="http://tempuri.org/ITamagotchiService/EatResponse")]
        System.Threading.Tasks.Task EatAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Sleep", ReplyAction="http://tempuri.org/ITamagotchiService/SleepResponse")]
        void Sleep(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Sleep", ReplyAction="http://tempuri.org/ITamagotchiService/SleepResponse")]
        System.Threading.Tasks.Task SleepAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Play", ReplyAction="http://tempuri.org/ITamagotchiService/PlayResponse")]
        void Play(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Play", ReplyAction="http://tempuri.org/ITamagotchiService/PlayResponse")]
        System.Threading.Tasks.Task PlayAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Hug", ReplyAction="http://tempuri.org/ITamagotchiService/HugResponse")]
        void Hug(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Hug", ReplyAction="http://tempuri.org/ITamagotchiService/HugResponse")]
        System.Threading.Tasks.Task HugAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/ApplyGameRules", ReplyAction="http://tempuri.org/ITamagotchiService/ApplyGameRulesResponse")]
        TamagotchiApp.Tamagotchi_Service.Tamagotchi ApplyGameRules(TamagotchiApp.Tamagotchi_Service.Tamagotchi tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/ApplyGameRules", ReplyAction="http://tempuri.org/ITamagotchiService/ApplyGameRulesResponse")]
        System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.Tamagotchi> ApplyGameRulesAsync(TamagotchiApp.Tamagotchi_Service.Tamagotchi tamagotchi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITamagotchiServiceChannel : TamagotchiApp.Tamagotchi_Service.ITamagotchiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TamagotchiServiceClient : System.ServiceModel.ClientBase<TamagotchiApp.Tamagotchi_Service.ITamagotchiService>, TamagotchiApp.Tamagotchi_Service.ITamagotchiService {
        
        public TamagotchiServiceClient() {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamagotchiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TamagotchiApp.Tamagotchi_Service.CompositeType GetDataUsingDataContract(TamagotchiApp.Tamagotchi_Service.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.CompositeType> GetDataUsingDataContractAsync(TamagotchiApp.Tamagotchi_Service.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void ResetTamagotchies() {
            base.Channel.ResetTamagotchies();
        }
        
        public System.Threading.Tasks.Task ResetTamagotchiesAsync() {
            return base.Channel.ResetTamagotchiesAsync();
        }
        
        public TamagotchiApp.Tamagotchi_Service.Tamagotchi[] GetAllTamagotchies() {
            return base.Channel.GetAllTamagotchies();
        }
        
        public System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.Tamagotchi[]> GetAllTamagotchiesAsync() {
            return base.Channel.GetAllTamagotchiesAsync();
        }
        
        public TamagotchiApp.Tamagotchi_Service.Tamagotchi GetTamagotchi(int id) {
            return base.Channel.GetTamagotchi(id);
        }
        
        public System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.Tamagotchi> GetTamagotchiAsync(int id) {
            return base.Channel.GetTamagotchiAsync(id);
        }
        
        public void AddTamagotchi(string name) {
            base.Channel.AddTamagotchi(name);
        }
        
        public System.Threading.Tasks.Task AddTamagotchiAsync(string name) {
            return base.Channel.AddTamagotchiAsync(name);
        }
        
        public void Eat(int id) {
            base.Channel.Eat(id);
        }
        
        public System.Threading.Tasks.Task EatAsync(int id) {
            return base.Channel.EatAsync(id);
        }
        
        public void Sleep(int id) {
            base.Channel.Sleep(id);
        }
        
        public System.Threading.Tasks.Task SleepAsync(int id) {
            return base.Channel.SleepAsync(id);
        }
        
        public void Play(int id) {
            base.Channel.Play(id);
        }
        
        public System.Threading.Tasks.Task PlayAsync(int id) {
            return base.Channel.PlayAsync(id);
        }
        
        public void Hug(int id) {
            base.Channel.Hug(id);
        }
        
        public System.Threading.Tasks.Task HugAsync(int id) {
            return base.Channel.HugAsync(id);
        }
        
        public TamagotchiApp.Tamagotchi_Service.Tamagotchi ApplyGameRules(TamagotchiApp.Tamagotchi_Service.Tamagotchi tamagotchi) {
            return base.Channel.ApplyGameRules(tamagotchi);
        }
        
        public System.Threading.Tasks.Task<TamagotchiApp.Tamagotchi_Service.Tamagotchi> ApplyGameRulesAsync(TamagotchiApp.Tamagotchi_Service.Tamagotchi tamagotchi) {
            return base.Channel.ApplyGameRulesAsync(tamagotchi);
        }
    }
}
